### ISSUE TITLE
[BOOK] Typos and Grammar

### ISSUE THREAD

**Issue by alex-mckenna** [SchrodingerZhu/VNMCC#2]
Hi @SchrodingerZhu,

I've had a chance to read more of the book now, it looks like a good entry-level introduction to Clash. Thanks again for your hard work :smile:

Some typos / other language errors I've found in the book:

## Position of the errors

- Line 20 of `chapter1.tex`: "gosing" -> "going"
- Line 68 of `chapter2.tex`: "operatior" -> "operator"
- Line 153 of `chapter2.tex`: "hexdecimal" -> "hexadecimal"
- Line  30 of `chapter3.tex`: The sentence "There is another fantastic thing you can also set a test bench for your circuits." isn't quite grammatically correct. I would recommend "Another fantastic thing you can do is create a test bench for your circuits."
- Line 139 of `chapter3.tex`: "Nothong" -> "Nothing"
- Line 3 of `chapter4.tex`: "What is CPU" -> "What is a CPU"
- Line 82 of `chapter4.tex`: "Infomation" -> "Information"

**Comment by SchrodingerZhu** [comment]
@alex-mckenna thanks! due to some personal stuffs(school works), I will get back to this repo after May 26th. Sorry for the delay.

**Comment by SchrodingerZhu** [comment]
should have been fixed in the latest commit.
